### ISSUE TITLE
能麻烦标注下运行环境及依赖吗？Python2/3均运行错误

### ISSUE THREAD

**Issue by whoooami** [rfyiamcool/jd_product_spider#3]
Python 2.
AttributeError: 'NoneType' object has no attribute 'Binary'

Python 3 
`
Traceback (most recent call last):
  File "models.py", line 57, in <module>
    db.connect()
  File "/usr/local/lib/python3.7/site-packages/peewee.py", line 3065, in connect
    self._state.set_connection(self._connect())
  File "/usr/local/lib/python3.7/site-packages/peewee.py", line 3965, in _connect
    conn = mysql.connect(db=self.database, **self.connect_params)
TypeError: __init__() got an unexpected keyword argument 'threadlocals'
`

Python 新手，抱歉

**Comment by whoooami** [comment]
MySQL-python 驱动问题，重装了。Python2环境正常了。运行表正常，但没有数据。
